### ISSUE TITLE
Switch Workspaces from Project Sidebar

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1131]
Currently, we need to switch workspaces with `File > Workspaces > Switch Workspace > Select a Workspace from the dropdown > Load Workspace`.  Since this is the most commonly used feature for workspaces, we want to streamline it.

The workspace is currently displayed in the Project sidebar:

![image](https://user-images.githubusercontent.com/24532731/200381492-05e6e38b-01d8-4316-b069-1bc16f72b9dd.png)

We would like to update this to be a combobox/dropdown with a sorted list of workspaces.  This will allow the workspace to be switched with two clicks.

**Comment by rat-moonshine** [comment]
This updated with following:

- Non-cropped popup in dropdown
- Fixed collection updates with new/save-as event
- Sorting fixed

**Comment by JoelProminic** [comment]
The dropdown size looks better, but I still see the workspaces are not sorted.

It should be fine to merge this issue, unless you think it is closely connected to #1135.  We may make some UI updates for this later, but this is a useful update that I would like to see available in the development branch.

**Comment by rat-moonshine** [comment]
I merged this issue in `master`. #1135 shouldn't create much headache now. Please, check.

**Comment by JoelProminic** [comment]
I confirmed this on master.  The sorting is fixed, and the [display issue](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1135#issuecomment-1311407519) for Switch Workspace is resolved as well.

I'm closing this issue. We will probably want some skin updates for this, but we'll work on this as part of #1132.
