### ISSUE TITLE
Build nsf database on Vagrant throws error

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#1249]
- This issue is Windows only
- I used Super.Human.Installer and Domino 12.0.1 to create a server instance
- I created an nsf database using Moonshine's `File -> New -> Domino On Disk Project`
- Tried `Project -> Build on Vagrant`
- Successfully connected to my server instance
- Build throws an error:
```
: Moonshine IDE™ Version 3.3.4, Build 1473
: Copyright © STARTcloud, Inc. 2015-2024. All rights reserved.
: Source code is under Apache License, Version 2.0
: https://github.com/Moonshine-IDE/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 33.1.1.856
: Zipping files from: C:\Users\Adrian\Documents\Repos\PieChartExample\PieChartNsf
: Trying to upload request to: http://restapi.mercury.planets.com:8080/file/upload. This may take some time..
: Requesting conversion job to: http://restapi.mercury.planets.com:8080/task
: Output: Starting NSFODP for file /tmp/restinterface/upload/38856C1E-831A-7403-BF4A-793B549B1CF0.zip
: Archive:  /tmp/restinterface/upload/38856C1E-831A-7403-BF4A-793B549B1CF0.zip
:    creating: formbuilder-src/main/
:   inflating: formbuilder-src/main/xml/PieChartNsf.xml  
:   inflating: nsfs/nsf-moonshine/build.properties  
:   inflating: nsfs/nsf-moonshine/pom.xml  
:   inflating: nsfs/nsf-moonshine/META-INF/MANIFEST.MF  
:    creating: nsfs/nsf-moonshine/odp/SharedElements/
:    creating: nsfs/nsf-moonshine/odp/WebContent/
:   inflating: nsfs/nsf-moonshine/odp/plugin.xml  
:   inflating: nsfs/nsf-moonshine/odp/AppProperties/database.properties  
:   inflating: nsfs/nsf-moonshine/odp/AppProperties/xspdesign.properties  
:    creating: nsfs/nsf-moonshine/odp/Code/Java/
:  extracting: nsfs/nsf-moonshine/odp/Code/dbscript.lsdb  
:   inflating: nsfs/nsf-moonshine/odp/Code/actions/Shared Actions  
:   inflating: nsfs/nsf-moonshine/odp/Code/actions/Shared Actions(1)  
:   inflating: nsfs/nsf-moonshine/odp/Code/Agents/ExampleJavaAgent.ja  
:   inflating: nsfs/nsf-moonshine/odp/Code/Agents/ExampleLotusScriptAgent.lsa  
:   inflating: nsfs/nsf-moonshine/odp/Code/Java/demo/Placeholder.java  
:   inflating: nsfs/nsf-moonshine/odp/Code/Java/demo/Placeholder.java.metadata  
:   inflating: nsfs/nsf-moonshine/odp/Code/ScriptLibraries/utils.ssjs.jss  
:   inflating: nsfs/nsf-moonshine/odp/Code/ScriptLibraries/utils.ssjs.jss.metadata  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/Footer.xsp  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/Footer.xsp-config  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/Footer.xsp.metadata  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingActionBar.xsp  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingActionBar.xsp-config  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingActionBar.xsp.metadata  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingsActionBar.xsp  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingsActionBar.xsp-config  
:   inflating: nsfs/nsf-moonshine/odp/CustomControls/GreetingsActionBar.xsp.metadata  
:   inflating: nsfs/nsf-moonshine/odp/Forms/Greeting.form  
:   inflating: nsfs/nsf-moonshine/odp/Forms/PieChartNsf.form  
:  extracting: nsfs/nsf-moonshine/odp/META-INF/MANIFEST.MF  
:   inflating: nsfs/nsf-moonshine/odp/Pages/HelloWorld.page  
:   inflating: nsfs/nsf-moonshine/odp/Resources/AboutDocument  
:   inflating: nsfs/nsf-moonshine/odp/Resources/IconNote  
:   inflating: nsfs/nsf-moonshine/odp/Resources/UsingDocument  
:   inflating: nsfs/nsf-moonshine/odp/SharedElements/Columns/Last Updated.column  
:   inflating: nsfs/nsf-moonshine/odp/SharedElements/Fields/Comment.field  
:   inflating: nsfs/nsf-moonshine/odp/SharedElements/Subforms/Footer.subform  
:   inflating: nsfs/nsf-moonshine/odp/Views/All By UNID.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Creation Date.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Form Used.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/All By UNID_5cBy Last Modified.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/All By UNID_5cCRUD_5c%form%.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/Greetings.view  
:   inflating: nsfs/nsf-moonshine/odp/Views/PieChartNsf.view  
:   inflating: nsfs/nsf-moonshine/odp/WebContent/WEB-INF/faces-config.xml  
:   inflating: nsfs/nsf-moonshine/odp/WebContent/WEB-INF/xsp.properties  
:   inflating: nsfs/nsf-moonshine/odp/XPages/Greeting.xsp  
:   inflating: nsfs/nsf-moonshine/odp/XPages/Greeting.xsp.metadata  
:   inflating: nsfs/nsf-moonshine/odp/XPages/Greetings.xsp  
:   inflating: nsfs/nsf-moonshine/odp/XPages/Greetings.xsp.metadata  
:   inflating: nsfs/nsf-moonshine/target/nsf-moonshine-domino-1.0.0.nsf  
:    creating: src/main/
:   inflating: src/main/formbuilder/PieChartNsf.dfb  
:   inflating: src/main/visualeditor/PieChartNsf.dve  
:    creating: visualeditor-src/main/
:   inflating: visualeditor-src/main/webapp/PieChartNsf.xml  
:   inflating: domino-pom.xml          
:   inflating: PieChartNsf.ondiskproj  
:   inflating: pom.xml                 
: Conversion failed with exit code: 1
: warning:  /tmp/restinterface/upload/38856C1E-831A-7403-BF4A-793B549B1CF0.zip appears to use backslashes as path separators
```

Most likely related to: #1134

**Comment by JoelProminic** [comment]
I pushed a quick fix for this to Super.Human.Installer in [this issue](https://github.com/Moonshine-IDE/Super.Human.Installer/issues/110).  @Aszusz had some remaining problems with the early testing on this.

**Comment by Aszusz** [comment]
@JoelProminic 
Build on Vagrant is still not working for me on Windows. Could you take a look at this log?
[build-on-vagrant.txt](https://github.com/Moonshine-IDE/Moonshine-IDE/files/14222779/build-on-vagrant.txt)

**Comment by JoelProminic** [comment]
@Aszusz, this is the relevant error:

    : [ERROR] Failed to execute goal org.openntf.maven:nsfodp-maven-plugin:3.8.1:generate-metadata (default-generate-metadata) on project nsf-moonshine-domino: Execution default-generate-metadata of goal org.openntf.maven:nsfodp-maven-plugin:3.8.1:generate-metadata failed: java.nio.file.AccessDeniedException: /tmp/nsfodp/20240209081119/nsfs/nsf-moonshine/odp/Code/Java/demo -> [Help 1]

This indicates the permissions are not set properly.  This is an issue I remember seeing before, but it was supposed to be fixed by [this command](TODO).

To debug this, connect to the VM with `vagrant ssh` and run:

    sudo ls -lhd /tmp/nsfodp/20240209081119/nsfs/nsf-moonshine/odp/Code/Java/demo 
    sudo ls -lh /tmp/nsfodp/20240209081119/nsfs/nsf-moonshine/odp/Code/Java/demo 
    # retest as java_user
    sudo su - java_user
    bash
    ls -lhd /tmp/nsfodp/20240209081119/nsfs/nsf-moonshine/odp/Code/Java/demo 
    ls -lh /tmp/nsfodp/20240209081119/nsfs/nsf-moonshine/odp/Code/Java/demo 

In each of these cases, you should see the owner is `java_user` and the group is `java_group`.  If you see something else, try runing this command:

    sudo chown -R java_user:java_group /tmp/nsfodp/20240209081119/

And check the pemissions again.

If you rerun Project > Build on Vagrant, you'll need to change the path based on the command output.

Let me know if you still have trouble with this.

**Comment by Aszusz** [comment]
When I do the first command I get no file or directory. This is my /tmp on this server:
```
startcloud@venus:~$ sudo ls /tmp
domino.pid
hsperfdata_java_user
restinterface
systemd-private-ea97ca3391d44b99a2037b2a5d01bdb9-cockpit.service-7yA2qX
systemd-private-ea97ca3391d44b99a2037b2a5d01bdb9-ModemManager.service-3Gw13j
systemd-private-ea97ca3391d44b99a2037b2a5d01bdb9-ntpsec.service-yEB4xW
systemd-private-ea97ca3391d44b99a2037b2a5d01bdb9-systemd-logind.service-bV1MX3
systemd-private-ea97ca3391d44b99a2037b2a5d01bdb9-systemd-resolved.service-jX3CDm
tomcat.8080.2312886284794258681
tomcat-docbase.8080.7182603184335134789
```
Is tmp cleared on server restart? Do I have to recreate the server and check during the initial run?

**Comment by Aszusz** [comment]
```
startcloud@venus:~$ sudo ls -lhd /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java/demo
drwxr-xr-x 2 java_user java_group 63 Feb  9 12:26 /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java/demo
startcloud@venus:~$ sudo ls -lh /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java/demo
total 8.0K
-rw-r--r-- 1 java_user java_group 274 Feb  9  2024 Placeholder.java
-rw-r--r-- 1 java_user java_group 320 Feb  9  2024 Placeholder.java.metadata
```
java_user and java_group seems to be correct. Do I need +x flag somewhere?

**Comment by Aszusz** [comment]
As java_user
```
java_user@venus:~$ ls -ldh /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java
drw-r--r-- 3 java_user java_group 18 Feb  9  2024 /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java
java_user@venus:~$ ls -ldh /tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java/demo
ls: cannot access '/tmp/nsfodp/20240209122646/nsfs/nsf-moonshine/odp/Code/Java/demo': Permission denied
```

**Comment by JoelProminic** [comment]
Can you SCP the zip file out of the VM for me and send it to me for testing?  Look for lines like these near the top of the output:

```
: Output: Starting NSFODP for file /tmp/restinterface/upload/487D032B-25B7-0191-801F-8E35585D688B.zip
: Archive:  /tmp/restinterface/upload/487D032B-25B7-0191-801F-8E35585D688B.zip
```

**Comment by JoelProminic** [comment]
If you prefer, we can discuss this in meeting.   I sent you the meeting info by email.

**Comment by JoelProminic** [comment]
After doing more tests with the unzipped directory, we found that the problem

    java_user@dev-1201:~$ ls -lh /tmp/nsfodp/20240209144605/nsfs/nsf-moonshine/odp/Code/Java
    ls: cannot access '/tmp/nsfodp/20240209144605/nsfs/nsf-moonshine/odp/Code/Java/demo': Permission denied
    total 0
    d????????? ? ? ? ?            ? demo

And this was caused because the directory was missing the "x" permission:

    java_user@dev-1201:~$ ls -lhd /tmp/nsfodp/20240209144605/nsfs/nsf-moonshine/odp/Code/Java
    drw-r--r-- 3 java_user java_group 18 Feb  9  2024 /tmp/nsfodp/20240209144605/nsfs/nsf-moonshine/odp/Code/Java

I was not aware of this, but for Linux, the "x" permission is required on directories to allow access.  Excerpt from [this page](https://www.redhat.com/sysadmin/linux-file-permissions-explained):

>This permission is very different on directories compared to files. Essentially, you can think of it as providing access to the directory. Having execute permission on a directory authorizes you to look at extended information on files in the directory (using ls -l, for instance) but also allows you to change your working directory (using cd) or pass through this directory on your way to a subdirectory underneath.
>
>Lacking execute permission on a directory can limit the other permissions in interesting ways. For example, how can you add a new file to a directory (by leveraging the write permission) if you can't access the directory's metadata to store the information for a new, additional file? You cannot. It is for this reason that directory-type files generally offer execute permission to one or more of the user owner, group owner, or others.

I'm not clear why the permission was wrong specifically for this directory.  I added this command to fix the problem in general:

    sudo find . -type d -exec chmod 744 {} +

I just committed my updates for this after doing some tests on macOS.  Please try this when you have a chance.

**Comment by JoelProminic** [comment]
I also created a form where I set all of the objects.  This triggered the same errors as above when opening and closing the form 

I uploaded the database here:
- blazeds.testprominic.com/PNITEST
- A55D78/MoonshineTests/temp/TestDominoVisualEditor_0209.nsf
- Form: TestDominoVisualEditor_0209

Checking the form in Designer, I found that the LotusScript objects were preserved properly, except for the form Initialize and Terminate.  The Formula and JavaScript objects were not preserved, but this was expected with the current limitations.

![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/cf6cd55d-d543-4dd3-8c7c-77d73b915e44)

**Comment by piotrzarzycki21** [comment]
@Aszusz @JoelProminic I have created fresh build 0.8.24 of SHI. You should get update once you run your dev 0.8.23

**Comment by Aszusz** [comment]
@JoelProminic @piotrzarzycki21 
Thank you guys, with the new 0.8.24 SHI version all cases related to PieChartExample run successfully on Windows. I'm closing this issue.

**Comment by JoelProminic** [comment]
Great!  Let me know if you run into any more problems.
