### ISSUE TITLE
[Domino Visual Editor] Remove Global Maven settings.xml Dependency

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#835]
By my understanding, we currently need to update the global Maven settings (i.e. ~/.m2/settings.xml) and add some configuration to allow Domino Visual Editor to work.  You can see more details for this in the description for #646.

However, we have already implemented a better way for this for the Domino On Disk project templates.  Instead of using the global settings.xml, we use a settings file that we define specifically for Moonshine Domino applications.  The Notes path and update site are configured in Moonshine > Settings > Domino.  You can see more details here:  https://github.com/prominic/Moonshine-IDE/issues/689#issuecomment-625479878

I'd like to have Domino Visual Editor use the same logic for this, so that the user can fully setup the environment from Moonshine only.

Please make this update in a branch.  If this is a quick update, we could consider including it in the quick fix release for #834.

**Comment by feather812002** [comment]
I try to work around this in today .
But I always get follow error:
![image](https://user-images.githubusercontent.com/8543391/121180071-1a1a8900-c869-11eb-8539-6e06d74fdd89.png)


I try follow steps to fix it ,but all not work .

1. I update the Moonshine IDE to 3.2.0 and download the lastest pkg install package from bamboo.
2. I try to update the Flex SDK to "V4.16.1 Harman AIR" and change the setting from Moonshine IDE.
3. I try to install the  Feathers SDK.
4. I try to  search the "actionScripts.valueObjects.ComponentTypes"  from Moonshinde IDE and VisualEditor and MockupVisualEditor , but nothing found from above all project .

So anyone have any idea how to fix it ?

> actionScripts.valueObjects.ComponentTypes
This package belong to which SDK ?

Thanks.

**Comment by piotrzarzycki21** [comment]
Following commit probably belongs to this issue. @feather812002 forgot add issue number to it, so I'm pasting it here so it would be referenced here. https://github.com/prominic/Moonshine-IDE/commit/016eb0ac9c5c0531e7a3e88c1aa330f44c4920bc

**Comment by feather812002** [comment]
This issue look like already fixed.
The domino visual editor project can loading the notes config path from global setting.xml 
and it can build success without any error.
![image](https://user-images.githubusercontent.com/8543391/124130929-f4f3f180-da87-11eb-9a07-c09f1fee295d.png)
and I confirm the project-level maven setting and Notes Programe Path not setting .
![image](https://user-images.githubusercontent.com/8543391/124131019-0e953900-da88-11eb-8b1a-fe4b619e0576.png)

**Comment by JoelProminic** [comment]
This is working for you because you already have the configuration defined in ~/.m2/settings.xml.   I confirmed that once I comment out the nsfodp configuration in in this file, I get errors like this when building Domino Visual Editor projects.

    : [ERROR] Failed to execute goal org.openntf.maven:nsfodp-maven-plugin:3.4.0:compile (default-compile) on project nsf-moonshine-domino: Execution default-compile of goal org.openntf.maven:nsfodp-maven-plugin:3.4.0:compile failed: Either the notesProgram or compilerServerUrl property must be supplied -> [Help 1] 

Instead, we want the user to setup the Notes application path and update site in Moonshine > Settings > Domino.  This will generate ~/Downloads/MoonshineSDKs/Domino/settings.xml.

I see with On Disk Project that Moonshine is populating Maven Settings File in the project Maven settings.  We can handle this the same way for Domino Visual Editor.  However, we need to make sure that the user can override the settings.xml path if desired.

I see that Domino Visual Editor has settings for "Notes Programe Path" and "Notes Platform Path".   Please remove these for now.   If the user needs custom settings for these variables, I would expect that they are already comfortable with On Disk Project.  In this case, I expect that they will be more comfortable creating a custom settings.xml in the project.   If we find a need for this in the future, we can revisit this feature.

**Comment by feather812002** [comment]
Okay ,after I review the On Disk Project into details , I found some code about this : 
`OnDiskMavenSettingsExporter.mavenSettingsPath = new FileLocation(targetUpdateSitePath.parent.resolvePath("settings.xml").nativePath);`

`if (OnDiskMavenSettingsExporter.mavenSettingsPath && OnDiskMavenSettingsExporter.mavenSettingsPath.fileBridge.exists)
			{
				pvo.mavenBuildOptions.settingsFilePath = OnDiskMavenSettingsExporter.mavenSettingsPath.fileBridge.nativePath; 
			}`

So , this is a fixed value at now for ODP project.

**Comment by feather812002** [comment]
Okay ,Now, I fixed this issue , I let it work same with ODP project![image](https://user-images.githubusercontent.com/8543391/124270263-a8222080-db44-11eb-8ab8-2772a82d4cee.png)

**Comment by JoelProminic** [comment]
I see that the Maven Settings File is now set on project creation, and this allows the project to build for me.

I would still like to see the Notes Programe Path and Notes Platform Path removed, though:
![image](https://user-images.githubusercontent.com/24532731/124290836-88293780-db19-11eb-895a-a27e733578b3.png)

**Comment by JoelProminic** [comment]
I see these extra settings are still present in the project.  @piotrzarzycki21 said he would take care of this.

**Comment by piotrzarzycki21** [comment]
> I see that the Maven Settings File is now set on project creation, and this allows the project to build for me.
> 
> I would still like to see the Notes Programe Path and Notes Platform Path removed, though:
> ![image](https://user-images.githubusercontent.com/24532731/124290836-88293780-db19-11eb-895a-a27e733578b3.png)

I have removed this settings. Is there some thing more we should do as part of this issue ?

**Comment by JoelProminic** [comment]
I confirmed the update, and confirmed the build still works.  That should be all for this issue.
