### ISSUE TITLE
Update Getting Started behavior for Subversion/SVN

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#849]
@JustinProminic reported an issue with enabling SVN and Git Integration on macOS Catalina or higher:
1. If you have set a path for the SVN binary already, clear it in the Moonshine settings
2. Open Getting Started. 
3. Find the Subversion Integration and Git Integration settings.  Note that both show a warning now
4. Click the gear icon next to Subversion Integration
5. Accept the prompt
6. The warning icons clear
7. Close and reopen Getting Started
8. Find the Subversion Integration and Git Integration settings.  BUG:  Both show a warning again

![image](https://user-images.githubusercontent.com/24532731/121728037-55f45f00-cab2-11eb-935f-632490d60f4d.png)

Part of the problem is that SVN is no longer associated with [XCode since macOS Catalina](https://github.com/prominic/Moonshine-SDK-Installer/issues/31). So, SVN now needs to be installed with Brew.  
9. Install SVN with brew if you haven't already
10. Open Moonshine > Settings > Subversion
11. Note that this is using the XCode path now.
12. Click "Change" and choose "/usr/bin/svn".  NOTE:  this is currently broken because of #839
13. After saving, the warnings should be cleared in Getting Started

We need to update this so that the permissions check requirement is for Git only.  We should have a separate check for SVN that depends on the SVN Binary only, similar to how the other SDKs work.

**Comment by rat-moonshine** [comment]
Understood. We need to de-couple Git and SVN check separately.

**Comment by JoelProminic** [comment]
Now that #839 is fixed, I can now set a path for the Subversion binary.  With a HomeBrew installation, the path is:

    /usr/local/Cellar/subversion/1.14.0_6/bin/svn


However, this is still not working properly for me:
1. Set the Subversion binary.  BUG:  The error message for the path does not clear until I save and reopen the Settings
1. Open and Select an SVN project.
1. BUG:  the menu still shows Subversion > Grant Permission
1. BUG:  the other SVN features are missing in the Subversion menu
1. Click Subversion > Grant Permission. This opens the Manage Repositories interface
1. Select/Add an entry for an SVN project
1. Click Checkout.  BUG:  nothing happens
1. Close the Manage Repositories window.  BUG:  The "Grant Permission" panel was opened behind this window.
1. Close the prompt
1. Check on Settings > Subversion > SVN Binary.  BUG:  This was updated to `/usr/local/Cellar/subversion/1.14.0_6/bin/usr/bin/svn`
1. Restart Moonshine
1. Check on Settings > Subversion > SVN Binary.  This path is still correct
1. Open Subversion > Manage Repositories
1. Try to checkout an SVN project.  BUG:  Nothing happens
1. Close the Manage Repositories panel.  BUG:  the Grant Permission prompt is open behind it again
1. Check on Settings > Subversion > SVN Binary.  BUG:  This was updated to `/usr/local/Cellar/subversion/1.14.0_6/bin/usr/bin/svn`
1. BUG:  Note that you see Git > Grant Permission in the menu now, even if you granted permission before.

**Comment by JoelProminic** [comment]
When I tried to use Git in Moonshine during the meeting today, I found that it is also broken now.  It keeps resetting to be based on the SVN path:  `/usr/local/Cellar/subversion/1.14.0_6/bin/usr/bin/git`

I tried changing this back to the GitHub path and restarting Moonshine, but it keeps resetting back to the above path each time I try to clone a project.

**Comment by rat-moonshine** [comment]
I should have asked you the earlier day only, if you still has the trouble please provide me the folder `/Library/Application Support/com.moonshine-ide` as a zip.

**Comment by rat-moonshine** [comment]
I'm starts de-coupling SVN and Git path from being one to separate.

**Comment by rat-moonshine** [comment]
@JoelProminic Since we can't rely on Xcode anymore for Subversion, what path we should detect for a possible existence on macOS, or foremost is we suggest to download any Subversion software that provides command-line (as slik-svn on Windows) which software it could be?

**Comment by rat-moonshine** [comment]
Part of the updates:

- [x] Detection and setup logic in Moonshine SDK Installer
- [x] Removal of 'Grant Permission' for SVN
- [ ] Manage Repositories updates

**Comment by rat-moonshine** [comment]
@JoelProminic I did a couple of changes in "Manage Repositories" following the https://github.com/Moonshine-IDE/Moonshine-IDE/issues/849#issuecomment-868392939 changes, please let me know if they sounds logical or we want to improve the procedures by some other way.

#### Case: Subversion Unavailable

**Create a new SVN entry**
Moonshine will prompt on the unavailability of Subversion, but user can continue to add an entry:
![image](https://user-images.githubusercontent.com/24370870/123414705-dc8c5e80-d5d1-11eb-95ad-19d1d288d8c6.png)

**Browse All**
Here's a list of repositories including Git and SVN to demonstrate, when Subversion is unavailable
![image](https://user-images.githubusercontent.com/24370870/123414798-f75ed300-d5d1-11eb-86af-807fad6424a5.png)

If user clicks on the "Browse All" button, SVN entry shall not be added into the tree-listing, because unfolding/browse Subversion entry requires Subversion executable:
![image](https://user-images.githubusercontent.com/24370870/123414872-0e052a00-d5d2-11eb-94b1-1a07cca78e52.png)

**SVN Entry Checkout**
It shall throw a console error, and open the Moonshine Settings so user can add a Subversion path:
![image](https://user-images.githubusercontent.com/24370870/123414962-2d03bc00-d5d2-11eb-8682-524079bfad75.png)

#### Case: Git Unavailable

**Git Entry Clone**
Prompt the user of Git unavailability and restrict to continue:
![image](https://user-images.githubusercontent.com/24370870/123415686-40fbed80-d5d3-11eb-92eb-51f1a54fb557.png)

With all these changes I guess we probably covered all the test-cases in "Manage Repositories" when Git or Subversion is unavailable. Let me know if I missed any or we need some course changes.

**Comment by JoelProminic** [comment]
I have a separate issue for the installation and configuration of SVN on macOS:  https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/31

My suggestion is to install SVN through Homebrew, but this could be a problem for MSDKI.

**Comment by rat-moonshine** [comment]
@JoelProminic I pushed a fix on Git and SVN path issues, specially where SVN paths was showing invalid due to an additional path-validation-test where Moonshine was trying to validate the given path with specific file-existence check.

Tested on macOS in following scenarios:

Platform | SDK | Path Value | Valid
-------------- | ---- | ------------- | -----------------------
macOS | Git | /Applications/Xcode/contents/Developer/usr/bin/git | Yes
macOS | Git | /Applications/Xcode/contents/Developer/usr/bin/someOtherExecutable | No
macOS | Git | /Documents/SomeOtherApp/Otherapp.app | Yes
macOS | Git | /Applications/Xcode/contents/Developer | Yes (if `usr/bin/git` exists)
macOS | SVN | /Applications/Xcode/contents/Developer | Yes (if `usr/bin/svn` exists)
macOS | SVN | /Applications/Xcode/contents/Developer/usr/bin/svn | Yes
macOS | SVN | /Applications/Xcode/contents/Developer/usr/bin/someOtherExecutable | No
macOS | SVN | /Documents/SomeOtherApp/Otherapp.app | Yes

If the changes still not resolve your problem you want to check `/Users/$user/Library/Application Support/com.moonshine-ide/Local Store/settings/SVNPlugin.xml` saved path, after setting the SVN path.

**Comment by JoelProminic** [comment]
I tried this:
1. Open Moonshine
2. Clear the paths for SVN and Git.
3. Confirm that SVNPlugin.xml and GitHubPlugin.xml are updated
4. NOTE:  I still see the SVN Path defined in VersionControlPlugin.xml
5. Restart Moonshine
6. Confirm that SVNPlugin.xml and GitHubPlugin.xml are not updated
7. Git > Grant Permission.  BUG:   both SVNPlugin.xml and GitHubPlugin.xml update to use the subversion path.  This matches the URL in VersionControlPlugin.xml


VersionControlPlugin.xml looks like this

```
<settings>
  
  <properties>
    <xcodePath>/usr/local/Cellar/subversion/1.14.0_6/bin</xcodePath>
  </properties>
  
</settings>
```


If I manually set the Git and SVN paths, then they are properly preserved now after a Moonshine restart.

**Comment by rat-moonshine** [comment]
> VersionControlPlugin.xml looks like this

Thank you, for the reference @JoelProminic . I was almost forgot this. 

I fixed a couple of things which was causing you this:

1. Cleared Git and SVN paths in Settings
2. Performing `Git -> Grant Permission` opens Repository Browser [Bug]
3. In Moonshine Settings, Git path auto-set as `/usr/local/Cellar/subversion/1.14.0_6/bin/usr/bin/git` [Bug]
4. In Moonshine Settings, SVN path auto-set as `/usr/local/Cellar/subversion/1.14.0_6/bin/usr/bin/svn` [Bug]

Please, try by the above steps again and see if you can reproduce the problems again.

**Comment by rat-moonshine** [comment]
@JoelProminic reported this in following steps:

1. Clear Git and SVN paths in Moonshine Settings
2. Open "Getting Started"
3. Enable "By Software" view
4. Configuration icon for "Git" entry is not showing, however it's showing in "By Feature" view
![image](https://user-images.githubusercontent.com/24370870/123770691-1a49f980-d8e8-11eb-9f2d-709b5d470146.png)

**Comment by rat-moonshine** [comment]
Following things fixed against https://github.com/Moonshine-IDE/Moonshine-IDE/issues/849#issuecomment-870422576:

- Showing configure icon for Subversion when it is not available, in Moonshine
- Removal of available-note (exclamation icon) based on Xcode/CommandLineTools presence for Subversion
- Opening Moonshine Settings upon clicking on configure icon for Subversion, instead of opening Xcode permission window

**Comment by JoelProminic** [comment]
When I first updated to the newest version, SVN and Git were in a bad state. I'm not sure how I had them set before the update:
- Git was set to be based on the SVN path instead of XCode
- SVN was not set

I suspect this but was a carry-over from the problems in the master build, but we need to be careful that we don't break the existing configuration on an update.

I didn't see this behavioron a fresh setup.  I installed the new build (branch build 412), and I saw this behavior:
1. Clear SVN and Git Path in Moonshine
2. Restart Moonshine
3. Getting Started opens.  Subversion is not set, and Git is set but shows a warning
4. Check the Settings.  Both the Git Binary and SVN Binary are not set
5. Git > Grant Permission
6. Clone a project - this works
7. Subversion > Manage Repositories 
8. Double-click a project.  It shows an error:  "Subversion is unavailable.  Unable to Browse the related repositories"
9. Try to checkout a project.  This takes you to Settings > Subversion, but does not close Manage REpositories.
10. Set the SVN binary and save
11. Open SVN > Manage Repositories and checkout a project - this works
12. Restart Moonshine again
13. Confirm that Git and SVN are set properly in the settings
14. Confirm that the menu shows Git > Manage Repositories and SVN > Manage Repositories

I confirmed your updates from your previous comment.  However, be aware that we may also need to have a similar Grant Permission step for the HomeBrew installation.  We can experiment with this more as we work on https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/31

**Comment by JoelProminic** [comment]
> When I first updated to the newest version, SVN and Git were in a bad state. I'm not sure how I had them set before the update:
> 
>     * Git was set to be based on the SVN path instead of XCode
> 
>     * SVN was not set

I confirmed that this is the behavior when I setup the paths on the branch build and then install the master build.  So, this should only be a problem when testing the builds.

However, we should review how this will work for:
- upgrading from the expected state for the 3.1.1 build.  Do we need extra cleanup logic here?
- Running on an older version of macOS that has SVN included in XCode.  In this case, the user will currently have to manually choose the paths for either case (which requires the CMD-Shift-G trick), at least until we implement https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/31

I haven't noticed any other remaining problems, so it is fine to merge this.

**Comment by rat-moonshine** [comment]
This issue now merged onto master.

**Comment by JoelProminic** [comment]
@feather812002, this should help resolve the errors you had for generating the on-disk-project update site.

**Comment by rat-moonshine** [comment]
While testing the `merged` build with @JoelProminic we noticed a couple of issues:

1. Clicking on configure icon for Git entry always opens me the 'grant permission' popup even when the permission has given. For Joel clicking on configure icon does nothing at all.
2. A manual refresh feature is not present in Haxe version of Getting Started (this could be a separate issue, though)
3. An auto-update check during opening of Haxe version of Getting Started seems to be not happening (needs to be investigated)

**Comment by rat-moonshine** [comment]
> Clicking on configure icon for Git entry always opens me the 'grant permission' popup even when the permission has given. For Joel clicking on configure icon does nothing at all.

This should be fixed now and should opens the git-settings view in case Git is already present.

I've moved the other two problems [here](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/782#issuecomment-875452964) as they are not related to the original issue here.

**Comment by JoelProminic** [comment]
I would like to do a full test on macOS (including clone and checkout examples) and a quick test on Windows, and if there are no problems  we can close this issue.

**Comment by rat-moonshine** [comment]
Here are my tests from SVN basic functionalities in Moonshine, on macOS and Windows.

**macOS : Using `homebrew` installation**
Function | Worked Properly | Observation
-------------- | ---------------- | -----------------
Checkout | Yes | Authentication window do not auto-close after providing auth-information for a private repository 
Commit | Yes | -
Update | Yes | Opened file/editor prompt for an update if the particular file downloaded with different editing time (#633 )

**Comment by piotrzarzycki21** [comment]
Cool if everything is working fine please close that ticket.

**Comment by rat-moonshine** [comment]
> Authentication window do not auto-close after providing auth-information for a private repository

I've fixed the authentication window close during SVN processes.
