### ISSUE TITLE
Rename File->Moonshine Helper Application

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#859]
From JustinProminic:

>Please change the name of File->Moonshine Helper Application to File->Launch Moonshine SDK Installer

**Comment by rat-moonshine** [comment]
Fixed and ready for a test.

**Comment by piotrzarzycki21** [comment]
Unfortunately I'm still seeing old text with build 1993. 

<img width="1662" alt="Screenshot 2021-06-22 at 16 39 30" src="https://user-images.githubusercontent.com/24554795/122945003-8c668f80-d378-11eb-8f55-71dac938366a.png">

**Comment by rat-moonshine** [comment]
Ah! Darn. I see the menu isn't using the value from LOCALE but static text https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFlexCoreBridgeImp.as#L462. I'll have this fixed.

**Comment by rat-moonshine** [comment]
Re-fix committed.

**Comment by piotrzarzycki21** [comment]
Text is in place. When I click on button I'm getting following window:

<img width="746" alt="Screenshot 2021-06-23 at 13 04 45" src="https://user-images.githubusercontent.com/24554795/123086556-d8224300-d423-11eb-8c9f-510463d2359e.png">

I believe installer should be launched if it's available.

**Comment by piotrzarzycki21** [comment]
Close issue and open new one if needed. Just note I have installed MSDKI non sandbox version.

**Comment by rat-moonshine** [comment]
The menu created with different thoughts in mind, let me recall them once. 

The menu not designed to open Moonshine SDK Installer application really, but a way to do that by the user itself. I think there were some Apple restrictions etc. involved for which we chose to do it this way.

The menu opens the popup providing a link to download the installer-application, I think we can have some basic detection process and have a button to launch the installer-application if exists, by continuing to have the popup with other information in it - this helps the user to understand what this menu is all about. 

Returning to the earlier procedures, once user clicks on the "Go to Download Page" button, the button label changes to "Validate & Set" - by this time Moonshine expects user have downloaded the installer-application and installed some SDKs that s/he wants. "Validate & Set" detects the items downloaded inside the "~/Downloads/MoonshineSDKs" folder and show the SDKs' information on screen. 

This is a very basic way we designed at that time, we could have this more complex or basic, though.

**Comment by JoelProminic** [comment]
Yeah, the AppStore reviewed had restrictions about launching other applications from the reviewed application, so this is the workaround that we used.   We could consider changing the behavior for the non-sandbox build, but this behavior is expected for now.

**Comment by JoelProminic** [comment]
I confirmed that the menu item is updated on macOS 10.15.7
