### ISSUE TITLE
Selecting file extensions in Project Search gives bad user experience

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#891]
1. Go to `Project > Search` or `Cmd + Shift + F`
2. Click `Select` (File name patterns)
- MINOR BUG: File extensions are not sorted. It's hard to find what you're looking for.
- MINOR BUG: When you click on the checkboxes nothing happens. To select/deselect an item you need to click on TEXT instead.

**Comment by rat-moonshine** [comment]
> File extensions are not sorted. It's hard to find what you're looking for

This should be fixed now, please check. 

> When you click on the checkboxes nothing happens. To select/deselect an item you need to click on TEXT instead

I couldn't able to reproduce this problem in my macOS tests. I able to select an entry by clicking on the square graphics.

**Comment by Aszusz** [comment]
> This should be fixed now, please check.

I confirm it's fixed.

> I couldn't able to reproduce this problem in my macOS tests. I able to select an entry by clicking on the square graphics.

That's weird. It's still not working for me and I remember @JoelProminic was able to reproduce it during our last call in another part of the application. Looked like a problem with Feathers' checkbox control.

**Comment by piotrzarzycki21** [comment]
> > File extensions are not sorted. It's hard to find what you're looking for
> 
> This should be fixed now, please check.
> 
> > When you click on the checkboxes nothing happens. To select/deselect an item you need to click on TEXT instead
> 
> I couldn't able to reproduce this problem in my macOS tests. I able to select an entry by clicking on the square graphics.

I can also reproduce that issue. Can you make some recording where you are trying to reproduce it ?

**Comment by rat-moonshine** [comment]
I did some re-tests. 

I admit this is strange - when I was testing through IDE-run/debugging, it was working correctly. 
When I re-test using sandbox installation, I see this not working. 

However, it suppose to have using the Feathers control produced by same Haxe compiler/setup that installs on my system. 

Do you guys check if this happens on non-sandbox installation too, or this is particular for the sandbox as I tested.

**Comment by piotrzarzycki21** [comment]
> Do you guys check if this happens on non-sandbox installation too, or this is particular for the sandbox as I tested.

Yes it happens on non sandbox.

**Comment by rat-moonshine** [comment]
Some more tests on this.

1. This time I re-compile the Haxe library locally, instead of using the one that already exists on the repository
2. Run the scenario using IDE (debug)
3. I able to produce the selection problem that reported by @Aszusz - so it's a sandbox independent problem

I assume why it worked for me earlier because I was using the Haxe SWC compiled sometime back - possibly using the earlier Feathers beta version. Re-compiling the SWC using latest beta (v5) now shows the problem even in IDE/debug run. 

@joshtynjala the selection trouble that @Aszusz [mentioned](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/891#issue-1011149508), could be something introduced in beta.5 (?)

**Comment by piotrzarzycki21** [comment]
I just wanted to add that previously it was working opposite. I could select Checkboxy clicking on Box, but couldn't do this while clicking on text. I think it should work in both cases.

**Comment by joshtynjala** [comment]
> the selection trouble that Aszusz, could be something introduced in beta.5 (?)

@rat-moonshine As a workaround, in _FileTypesCallout.hx_, add `check.focusEnabled = false`.

The `ItemRenderer` excludes children that are focusable when determining if it should "trigger" or not. By disabling focus on the `Check`, it will allow the `ItemRenderer` to trigger.

I think that I need to adjust the custom hit test to account for `mouseChildren` and `mouseEnabled`. Then, you won't need to set `focusEnabled = false` because you already have `mouseEnabled = false`.

**Comment by joshtynjala** [comment]
> I think that I need to adjust the custom hit test to account for mouseChildren and mouseEnabled. Then, you won't need to set focusEnabled = false because you already have mouseEnabled = false.

feathersui/feathersui-openfl@415f5994d83fcd2c87896a6e35c6c8864ac67372

**Comment by rat-moonshine** [comment]
> As a workaround, in FileTypesCallout.hx, add check.focusEnabled = false.

For now, I have made the changes as suggested by @joshtynjala . This makes the expected behaviour in this scenario. We can close this issue if everything looks good, @Aszusz .

**Comment by Aszusz** [comment]
Everything looks good, closing the issue.
